### ISSUE TITLE
Some thumbor filters are not enabled by default

### ISSUE THREAD

**Issue by javiercejudo** [APSL/docker-thumbor#89] opened 2018-02-22 04:51 UTC
The current [list of enabled filters][filters-conf] in the image does not include some of the [thumbor filters][thumbor-filters] as of 6.3.0 (the version of the latest image tag in dockerhub), eg: `focal`, `background_color` and others.

Is the list outdated or are there other reasons?

[filters-conf]: https://github.com/APSL/docker-thumbor/blob/a1bf9bd1bf9520f02fa57ba1a7cd66778edc3f4b/thumbor/conf/thumbor.conf.tpl#L534-L540
[thumbor-filters]: https://github.com/thumbor/thumbor/blob/b7cf77352375ab182071a64b0da513006c310aed/thumbor/config.py#L286-L318

**Comment by gingerlime** [comment] 2018-07-29 13:04
@javiercejudo I just bumped into the [same problem](https://github.com/thumbor/thumbor/issues/1101) without realizing the missing `FILTERS` was the cause. The latest / 6.5.1 tag of [minimalcompact/thumbor](https://github.com/MinimalCompact/thumbor) has all filters by default, unless you override it. (see https://github.com/MinimalCompact/thumbor/commit/efdee768134e7951630d8fb9a0d9bcbf2a534399)

Alternatively, you can manually set the `FILTERS` env to include all available filters.

**Comment by eduherraiz** [comment] 2021-11-17 18:28
All this filters will be included in the new 6.7.5 release

**Closed as completed by eduherraiz** 2021-11-17 18:28 UTC
